sudo: required
dist: trusty
language: cpp
compiler: g++
install: export CXX="g++-5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
os:
  - linux
before_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..
  - pwd
script:
  - pwd
  - cmake --build . --target run_bankingApplication_tests
  - ./application_test/run_bankingApplication_tests
