language: cpp
sudo: required
dist: trusty
compiler:
  - clang
os:
  - linux
before_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..
script:
  - cmake --build ./cmake-build --target run_bankingApplication_tests
  - ./cmake-build/application_test/run_bankingApplication_tests
