language: cpp
sudo: required
dist: trusty
compiler:
  - clang
os:
  - linux
before_script:
  - mkdir cmake-build
  - cd cmake-build
  - cmake ..
  - pwd
script:
  - pwd
  - cmake --build . --target run_bankingApplication_tests
  - ./application_test/run_bankingApplication_tests
